use crate::{
    errors::Result,
    filesystem,
    generator::Generator,
};

pub struct WorkspaceGenerator;

impl Generator for WorkspaceGenerator {
    fn generate(&self) -> Result<()> {
        filesystem::create_dir("generated")?;
        filesystem::write(
            "generated/README.md",
            "# Generated by Esprit Builder\n",
        )?;

        Ok(())
    }
}
