[package]
publish = false
name = "esprit-index"
version.workspace = true
edition.workspace = true
description = "Esprit AI workspace component"
license = "MIT"
repository = "https://github.com/krtvysinghh/Esprit"
homepage = "https://github.com/krtvysinghh/Esprit"
documentation = "https://github.com/krtvysinghh/Esprit"
readme = "README.md"

[dependencies]
anyhow.workspace      = true
ignore.workspace      = true
directories.workspace = true
rusqlite.workspace    = true
tantivy.workspace     = true
tracing.workspace     = true
petgraph = "0.8.3"
toml.workspace = true
serde_json.workspace = true
esprit-utils = { version = "0.1.0", path = "../esprit-utils" }
esprit-embeddings = { version = "0.1.0", path = "../esprit-embeddings" }
esprit-vectors = { version = "0.1.0", path = "../esprit-vectors" }
