[package]
publish = false
name = "esprit-plugins"
version.workspace = true
edition.workspace = true
description = "Esprit AI workspace component"
license = "MIT"
repository = "https://github.com/krtvysinghh/Esprit"
homepage = "https://github.com/krtvysinghh/Esprit"
documentation = "https://github.com/krtvysinghh/Esprit"
readme = "README.md"

[dependencies]
anyhow.workspace = true
wasmtime = "48.0.0"
