[package]
name="esprit-daemon"
version.workspace=true
edition.workspace=true
description = "Esprit AI workspace component"
license = "MIT"
repository = "https://github.com/krtvysinghh/Esprit"
homepage = "https://github.com/krtvysinghh/Esprit"
documentation = "https://github.com/krtvysinghh/Esprit"
readme = "README.md"

[dependencies]
anyhow.workspace=true
notify.workspace=true
crossbeam-channel="0.5"
esprit-index={version = "0.1.0", path = "../esprit-index" }
