[package]
name="esprit-daemon"
version.workspace=true
edition.workspace=true
description = "Esprit AI workspace component"
license = "MIT"
repository = "https://github.com/krtvysinghh/Esprit"
homepage = "https://github.com/krtvysinghh/Esprit"
documentation = "https://github.com/krtvysinghh/Esprit"
readme = "README.md"

[dependencies]
anyhow.workspace=true
notify.workspace=true
crossbeam-channel="0.5"
esprit-index={version = "0.1.0", path = "../esprit-index" }

tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tokio-util = "0.7"
chrono = "0.4"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "signal",
    "sync",
    "time"
]}
tracing = "0.1"