[package]
name="esprit-api"
version.workspace=true
edition.workspace=true
description = "Esprit AI workspace component"
license = "MIT"
repository = "https://github.com/krtvysinghh/Esprit"
homepage = "https://github.com/krtvysinghh/Esprit"
documentation = "https://github.com/krtvysinghh/Esprit"
readme = "README.md"

[dependencies]
anyhow.workspace=true
axum="0.8"
tokio={version="1",features=["full"]}
serde.workspace=true
serde_json.workspace=true
esprit-rag={version = "0.1.0", path = "../esprit-rag" }
esprit-index={version = "0.1.0", path = "../esprit-index" }
tracing.workspace = true

tokio-stream = "0.1"
futures-core = "0.3"
