[package]
name = "esprit-rag"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
esprit-index = { path = "../esprit-index" }
esprit-ai = { path = "../esprit-ai" }

esprit-embeddings = { path = "../esprit-embeddings" }

esprit-memory = { path = "../esprit-memory" }
