name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --workspace --release
      - run: cargo test --workspace
