[package]
name = "esprit-desktop"
version.workspace = true
edition.workspace = true
description = "Esprit AI workspace component"
license = "MIT"
repository = "https://github.com/krtvysinghh/Esprit"
homepage = "https://github.com/krtvysinghh/Esprit"
documentation = "https://github.com/krtvysinghh/Esprit"
readme = "README.md"

[dependencies]
tauri = { version = "2", features = ["shell-open", "clipboard-manager"] }
tokio = { version = "1", features = ["full"] }
esprit-rag = { version = "0.1.0", path = "../crates/esprit-rag" }
esprit-api = {version = 0.1.0", path = "../crates/esprit-api" }
